#!/bin/sh
# render.sh -- generate tool-specific color adapters from a semantic palette.
#
# Reads palettes/<theme>.json and, for each mode (dark, light), emits four
# build artifacts into generated/:
#
#   <theme>-<mode>.wezterm.lua   -- a colors table applied as config.colors
#   <theme>-<mode>.tmux.conf     -- the status-bar styling block
#   <theme>-<mode>.nvim.lua      -- a highlight-group adapter (function)
#   <theme>-<mode>/palette.sh    -- agent-state COLOR_* adapter (NOT spaceflight)
#
# Everything under generated/ is a build artifact: never hand-edit, never
# commit (see .gitignore). Re-running overwrites in place (idempotent).
#
# Usage:
#   render.sh            render all palettes (same as --all)
#   render.sh --all      render every palettes/*.json
#   render.sh <theme>    render just palettes/<theme>.json
#
# POSIX sh; needs `jq`.

set -eu

SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
PALETTES_DIR="$SCRIPT_DIR/palettes"
GEN_DIR="$SCRIPT_DIR/generated"

if ! command -v jq >/dev/null 2>&1; then
  printf 'render.sh: error: jq is required but not found on PATH.\n' >&2
  exit 1
fi

# g <palette-file> <mode> <key>  -> prints the hex/string value.
g() { jq -r --arg m "$2" --arg k "$3" '.[$m][$k]' "$1"; }
# a <palette-file> <mode> <index>  -> prints ansi[index].
a() { jq -r --arg m "$2" --argjson i "$3" '.[$m].ansi[$i]' "$1"; }
# ag <palette-file> <mode> <agent-key>  -> prints agent.<key>.
ag() { jq -r --arg m "$2" --arg k "$3" '.[$m].agent[$k]' "$1"; }

# render_mode <palette-file> <theme> <mode>
render_mode() {
  pf=$1
  theme=$2
  mode=$3

  # Pull every semantic role once.
  bg=$(g "$pf" "$mode" bg)
  fg=$(g "$pf" "$mode" fg)
  surface=$(g "$pf" "$mode" surface)
  overlay=$(g "$pf" "$mode" overlay)
  muted=$(g "$pf" "$mode" muted)
  subtle=$(g "$pf" "$mode" subtle)
  accent=$(g "$pf" "$mode" accent)
  accent2=$(g "$pf" "$mode" accent2)
  warn=$(g "$pf" "$mode" warn)
  error=$(g "$pf" "$mode" error)
  ok=$(g "$pf" "$mode" ok)
  selection_bg=$(g "$pf" "$mode" selection_bg)

  # ANSI 0-15.
  c0=$(a "$pf" "$mode" 0);  c1=$(a "$pf" "$mode" 1)
  c2=$(a "$pf" "$mode" 2);  c3=$(a "$pf" "$mode" 3)
  c4=$(a "$pf" "$mode" 4);  c5=$(a "$pf" "$mode" 5)
  c6=$(a "$pf" "$mode" 6);  c7=$(a "$pf" "$mode" 7)
  c8=$(a "$pf" "$mode" 8);  c9=$(a "$pf" "$mode" 9)
  c10=$(a "$pf" "$mode" 10); c11=$(a "$pf" "$mode" 11)
  c12=$(a "$pf" "$mode" 12); c13=$(a "$pf" "$mode" 13)
  c14=$(a "$pf" "$mode" 14); c15=$(a "$pf" "$mode" 15)

  agent_working=$(ag "$pf" "$mode" working)
  agent_needs_input=$(ag "$pf" "$mode" needs_input)
  agent_done=$(ag "$pf" "$mode" done)
  agent_idle=$(ag "$pf" "$mode" idle)

  base="$GEN_DIR/$theme-$mode"

  # -------------------------------------------------------------------------
  # 1. wezterm -- a Lua colors table applied as config.colors.
  # -------------------------------------------------------------------------
  cat >"$base.wezterm.lua" <<EOF
-- GENERATED by dotfiles/themes/render.sh -- do not edit.
-- theme: $theme   mode: $mode
-- Applied as \`config.colors\` in wezterm/appearance.lua.
return {
  background = '$bg',
  foreground = '$fg',
  cursor_bg = '$accent',
  cursor_border = '$accent',
  cursor_fg = '$bg',
  selection_bg = '$selection_bg',
  selection_fg = '$fg',
  ansi = {
    '$c0', '$c1', '$c2', '$c3',
    '$c4', '$c5', '$c6', '$c7',
  },
  brights = {
    '$c8', '$c9', '$c10', '$c11',
    '$c12', '$c13', '$c14', '$c15',
  },
}
EOF

  # -------------------------------------------------------------------------
  # 2. tmux -- the status-bar styling block. Mirrors the STRUCTURE of the
  #    original inline block in tmux.conf; only colors are substituted from the
  #    palette. The #{@agent_glyphs} references belong to the agent feature and
  #    are preserved verbatim.
  # -------------------------------------------------------------------------
  cat >"$base.tmux.conf" <<EOF
# GENERATED by dotfiles/themes/render.sh -- do not edit.
# theme: $theme   mode: $mode
# Status-bar styling for the active theme. Sourced by tmux.conf via the stable
# generated/current.tmux.conf indirection (see switch-theme). Structure mirrors
# the original inline Rose Pine block; colors come from palettes/$theme.json.

set -g status on
set -g status-interval 5
set -g status-position top
set -g status-justify left

# Overall bar background/foreground.
set -g status-style "bg=$surface,fg=$fg"

# Left: session name on an accent background.
set -g status-left-length 40
set -g status-left "#[bg=$accent,fg=$bg,bold] #S #[bg=$surface,fg=$accent]"

# Right: hostname then date/time, muted so it doesn't shout.
set -g status-right-length 80
set -g status-right "#[fg=$accent2] #H #[fg=$muted]| #[fg=$subtle]%Y-%m-%d #[fg=$fg]%H:%M "

# Window list: inactive windows muted, the active one highlighted.
# #{@agent_glyphs} is the agent-status overlay (one glyph per running agent in
# the window; empty when none). #W is the real window name.
setw -g window-status-format "#[fg=$muted] #I:#W #{@agent_glyphs}"
setw -g window-status-current-format "#[bg=$overlay,fg=$warn,bold] #I:#W #{@agent_glyphs}"
setw -g window-status-separator ""

# Pane borders: subtle for inactive, accent2 for the active pane.
set -g pane-border-style "fg=$overlay"
set -g pane-active-border-style "fg=$accent2"

# Messages / command prompt line.
set -g message-style "bg=$overlay,fg=$fg"
set -g message-command-style "bg=$overlay,fg=$fg"

# Copy-mode selection highlight.
setw -g mode-style "bg=$selection_bg,fg=$fg"
EOF

  # -------------------------------------------------------------------------
  # 3. nvim -- a highlight-group adapter. Returns a function that applies a
  #    minimal-but-real colorscheme via nvim_set_hl. statusline.lua reads
  #    PmenuSel / Directory / Visual after this loads, so those are defined
  #    with sensible fg/bg.
  # -------------------------------------------------------------------------
  cat >"$base.nvim.lua" <<EOF
-- GENERATED by dotfiles/themes/render.sh -- do not edit.
-- theme: $theme   mode: $mode
-- Returns a function that applies a minimal highlight scheme. Loaded by
-- nvim/lua/colorscheme.lua. Colors come from palettes/$theme.json.
local hl = {
  bg = '$bg',
  fg = '$fg',
  surface = '$surface',
  overlay = '$overlay',
  muted = '$muted',
  subtle = '$subtle',
  accent = '$accent',
  accent2 = '$accent2',
  warn = '$warn',
  error = '$error',
  ok = '$ok',
  selection_bg = '$selection_bg',
}

return function()
  local set = vim.api.nvim_set_hl
  set(0, 'Normal',       { fg = hl.fg, bg = hl.bg })
  set(0, 'NormalFloat',  { fg = hl.fg, bg = hl.surface })
  set(0, 'Comment',      { fg = hl.muted, italic = true })
  set(0, 'Constant',     { fg = hl.accent2 })
  set(0, 'String',       { fg = hl.ok })
  set(0, 'Statement',    { fg = hl.accent })
  set(0, 'Identifier',   { fg = hl.subtle })
  set(0, 'Type',         { fg = hl.accent2 })
  set(0, 'Visual',       { bg = hl.selection_bg })
  set(0, 'Pmenu',        { fg = hl.fg, bg = hl.surface })
  set(0, 'PmenuSel',     { fg = hl.bg, bg = hl.accent })
  set(0, 'Directory',    { fg = hl.accent2 })
  set(0, 'LineNr',       { fg = hl.muted })
  set(0, 'CursorLineNr', { fg = hl.warn, bold = true })
  set(0, 'StatusLine',   { fg = hl.fg, bg = hl.surface })
  set(0, 'DiagnosticError', { fg = hl.error })
  set(0, 'DiagnosticWarn',  { fg = hl.warn })
  set(0, 'DiagnosticInfo',  { fg = hl.accent2 })
  set(0, 'DiagnosticHint',  { fg = hl.muted })
end
EOF

  # -------------------------------------------------------------------------
  # 4. agent-state palette.sh -- mirrors the CONTRACT of
  #    tmux/themes/spaceflight/palette.sh (same COLOR_* names + export line) but
  #    lives here in generated/. Provided for completeness/future use; it does
  #    NOT replace or touch the spaceflight file.
  # -------------------------------------------------------------------------
  mkdir -p "$base"
  cat >"$base/palette.sh" <<EOF
# GENERATED by dotfiles/themes/render.sh -- do not edit.
# theme: $theme   mode: $mode
# Agent-state color adapter. Mirrors the contract of
# tmux/themes/spaceflight/palette.sh (identical COLOR_* names) but is generated
# from palettes/$theme.json. Provided for completeness; the spaceflight glyph
# renderer still sources its own palette.sh today.

COLOR_WORKING="$agent_working"
COLOR_NEEDS_INPUT="$agent_needs_input"
COLOR_DONE="$agent_done"
COLOR_IDLE="$agent_idle"

export COLOR_WORKING COLOR_NEEDS_INPUT COLOR_DONE COLOR_IDLE
EOF

  printf '  rendered %s (%s)\n' "$theme" "$mode"
}

# render_theme <theme>
render_theme() {
  theme=$1
  pf="$PALETTES_DIR/$theme.json"
  if [ ! -f "$pf" ]; then
    printf 'render.sh: error: no palette: %s\n' "$pf" >&2
    return 1
  fi
  if ! jq -e '.dark and .light' "$pf" >/dev/null 2>&1; then
    printf 'render.sh: error: palette %s missing dark/light keys or invalid JSON\n' "$pf" >&2
    return 1
  fi
  mkdir -p "$GEN_DIR"
  render_mode "$pf" "$theme" dark
  render_mode "$pf" "$theme" light
}

main() {
  arg=${1:---all}
  case "$arg" in
    --all)
      for pf in "$PALETTES_DIR"/*.json; do
        [ -e "$pf" ] || continue
        theme=$(basename "$pf" .json)
        render_theme "$theme"
      done
      ;;
    *)
      render_theme "$arg"
      ;;
  esac
}

main "$@"
