#!/bin/sh
# render.sh -- generate native theme files from a semantic palette.
#
# The theming model is "native tool theme dirs": for a given palette we emit one
# theme file per tool, in that tool's OWN theme-discovery directory, in that
# tool's native format. Each tool then switches themes natively -- there is no
# central controller, no "active" file, no current.* indirection.
#
# A palette is resolved as either:
#   * a NAME  -> palettes/<name>.json   (the baked-in public palettes), or
#   * a PATH  -> any *.json file        (local / third-party palettes, e.g. a
#                                         brand palette kept OUTSIDE this repo).
#
# For the resolved palette (with `dark` and `light` sub-objects; keys:
# bg,fg,surface,overlay,muted,subtle,accent,accent2,warn,error,ok,
# selection_bg,ansi[16],agent{working,needs_input,done,idle}) it emits:
#
#   wezterm  -> $WEZTERM_COLORS_DIR/<name>-dark.toml, <name>-light.toml
#   nvim     -> $NVIM_COLORS_DIR/<name>-dark.lua,     <name>-light.lua
#   opencode -> $OPENCODE_THEMES_DIR/<name>.json      (one file, both modes)
#   tmux     -> $TMUX_THEMES_DIR/<name>-dark.conf,     <name>-light.conf
#
# Switching, per tool:
#   wezterm  set config.color_scheme = '<name>-dark' (or use the scheme picker);
#            wezterm auto-scans ~/.config/wezterm/colors/*.toml.
#   nvim     :colorscheme <name>-dark
#   opencode set the theme in opencode's config; it follows its own light/dark.
#   tmux     source the chosen conf from tmux.conf (has no native theme registry).
#
# Output dirs default to the tools' real ~/.config locations but are overridable
# via the env vars named above (for testing against scratch dirs). Everything is
# idempotent: re-running overwrites outputs in place.
#
# Usage:
#   render.sh <name>     render palettes/<name>.json into all four tools
#   render.sh <path>     render an arbitrary palette .json (e.g. a local brand)
#   render.sh --all      render every baked-in palette in palettes/
#
# POSIX sh; needs `jq`.

set -eu

SCRIPT_DIR=$(cd "$(dirname "$0")" && pwd)
PALETTES_DIR="$SCRIPT_DIR/palettes"

# ---------------------------------------------------------------------------
# Native output dirs (overridable via env for testing against scratch dirs).
# ---------------------------------------------------------------------------
: "${XDG_CONFIG_HOME:=$HOME/.config}"
: "${WEZTERM_COLORS_DIR:=$XDG_CONFIG_HOME/wezterm/colors}"
: "${NVIM_COLORS_DIR:=$XDG_CONFIG_HOME/nvim/colors}"
: "${OPENCODE_THEMES_DIR:=$XDG_CONFIG_HOME/opencode/themes}"
: "${TMUX_THEMES_DIR:=$XDG_CONFIG_HOME/tmux/themes}"

if ! command -v jq >/dev/null 2>&1; then
  printf 'render.sh: error: jq is required but not found on PATH.\n' >&2
  exit 1
fi

# g <palette-file> <mode> <key>  -> prints the hex/string value.
g() { jq -r --arg m "$2" --arg k "$3" '.[$m][$k]' "$1"; }
# a <palette-file> <mode> <index>  -> prints ansi[index].
a() { jq -r --arg m "$2" --argjson i "$3" '.[$m].ansi[$i]' "$1"; }

# -----------------------------------------------------------------------------
# wezterm: two TOML color files (one per mode). Auto-discovered by wezterm from
# ~/.config/wezterm/colors/*.toml; user schemes override built-ins. The
# [metadata] name is what wezterm registers the scheme as, and we make it equal
# the filename stem so `config.color_scheme = '<name>-<mode>'` selects it.
# -----------------------------------------------------------------------------
render_wezterm() {
  pf=$1; name=$2; mode=$3
  bg=$(g "$pf" "$mode" bg)
  fg=$(g "$pf" "$mode" fg)
  accent=$(g "$pf" "$mode" accent)
  selection_bg=$(g "$pf" "$mode" selection_bg)
  c0=$(a "$pf" "$mode" 0);  c1=$(a "$pf" "$mode" 1)
  c2=$(a "$pf" "$mode" 2);  c3=$(a "$pf" "$mode" 3)
  c4=$(a "$pf" "$mode" 4);  c5=$(a "$pf" "$mode" 5)
  c6=$(a "$pf" "$mode" 6);  c7=$(a "$pf" "$mode" 7)
  c8=$(a "$pf" "$mode" 8);  c9=$(a "$pf" "$mode" 9)
  c10=$(a "$pf" "$mode" 10); c11=$(a "$pf" "$mode" 11)
  c12=$(a "$pf" "$mode" 12); c13=$(a "$pf" "$mode" 13)
  c14=$(a "$pf" "$mode" 14); c15=$(a "$pf" "$mode" 15)

  mkdir -p "$WEZTERM_COLORS_DIR"
  cat >"$WEZTERM_COLORS_DIR/$name-$mode.toml" <<EOF
# GENERATED by dotfiles/themes/render.sh -- do not edit.
# palette: $name   mode: $mode
# A wezterm color scheme. wezterm auto-scans ~/.config/wezterm/colors/*.toml and
# registers each by its [metadata] name. Select with:
#   config.color_scheme = '$name-$mode'   (or the built-in scheme picker).
[metadata]
name = "$name-$mode"

[colors]
foreground = "$fg"
background = "$bg"
cursor_bg = "$accent"
cursor_border = "$accent"
cursor_fg = "$bg"
selection_bg = "$selection_bg"
selection_fg = "$fg"
ansi = ["$c0", "$c1", "$c2", "$c3", "$c4", "$c5", "$c6", "$c7"]
brights = ["$c8", "$c9", "$c10", "$c11", "$c12", "$c13", "$c14", "$c15"]
EOF
}

# -----------------------------------------------------------------------------
# nvim: a colorscheme file per mode, loadable via `:colorscheme <name>-<mode>`.
# It sets termguicolors + colors_name and applies the highlight set. statusline.lua
# reads PmenuSel / Directory / Visual after the colorscheme loads, so those are
# defined here.
# -----------------------------------------------------------------------------
render_nvim() {
  pf=$1; name=$2; mode=$3
  bg=$(g "$pf" "$mode" bg)
  fg=$(g "$pf" "$mode" fg)
  surface=$(g "$pf" "$mode" surface)
  muted=$(g "$pf" "$mode" muted)
  subtle=$(g "$pf" "$mode" subtle)
  accent=$(g "$pf" "$mode" accent)
  accent2=$(g "$pf" "$mode" accent2)
  warn=$(g "$pf" "$mode" warn)
  error=$(g "$pf" "$mode" error)
  ok=$(g "$pf" "$mode" ok)
  selection_bg=$(g "$pf" "$mode" selection_bg)

  mkdir -p "$NVIM_COLORS_DIR"
  cat >"$NVIM_COLORS_DIR/$name-$mode.lua" <<EOF
-- GENERATED by dotfiles/themes/render.sh -- do not edit.
-- palette: $name   mode: $mode
-- A Neovim colorscheme. Load with :colorscheme $name-$mode. Colors come from
-- the palette's semantic roles. statusline.lua reads PmenuSel/Directory/Visual.
vim.o.termguicolors = true
vim.cmd('highlight clear')
if vim.fn.exists('syntax_on') == 1 then
  vim.cmd('syntax reset')
end
vim.g.colors_name = '$name-$mode'
local set = vim.api.nvim_set_hl
set(0, 'Normal',       { fg = '$fg', bg = '$bg' })
set(0, 'NormalFloat',  { fg = '$fg', bg = '$surface' })
set(0, 'Comment',      { fg = '$muted', italic = true })
set(0, 'Constant',     { fg = '$accent2' })
set(0, 'String',       { fg = '$ok' })
set(0, 'Statement',    { fg = '$accent' })
set(0, 'Identifier',   { fg = '$subtle' })
set(0, 'Type',         { fg = '$accent2' })
set(0, 'Visual',       { bg = '$selection_bg' })
set(0, 'Pmenu',        { fg = '$fg', bg = '$surface' })
set(0, 'PmenuSel',     { fg = '$bg', bg = '$accent' })
set(0, 'Directory',    { fg = '$accent2' })
set(0, 'LineNr',       { fg = '$muted' })
set(0, 'CursorLineNr', { fg = '$warn', bold = true })
set(0, 'StatusLine',   { fg = '$fg', bg = '$surface' })
set(0, 'DiagnosticError', { fg = '$error' })
set(0, 'DiagnosticWarn',  { fg = '$warn' })
set(0, 'DiagnosticInfo',  { fg = '$accent2' })
set(0, 'DiagnosticHint',  { fg = '$muted' })
EOF
}

# -----------------------------------------------------------------------------
# opencode: one theme JSON carrying BOTH modes, built with jq so hex values are
# injected safely and the output is valid JSON.
#
# LAYERED model (matches the look of opencode's built-in `system` theme, but with
# exact palette colors): the BASE background INHERITS the terminal, while the
# panel/element background LAYERS use palette hex, and every foreground/accent
# role is palette hex. Reference shape (validated live in David's opencode, build
# 1.18.16): ~/.config/opencode/themes/rosepine-layered.json.
#
#   background        -> "none"      (literal string; inherit the terminal bg)
#   backgroundPanel   -> surface hex (the panel layer)
#   backgroundElement -> overlay hex (the element layer)
#   diffContextBg     -> "none"      (inherit, like the base)
#   *everything else* -> palette hex (foregrounds, accents, borders, diff/md/syntax)
# We emit a `defs` block of named palette colors (per mode) and reference them by
# name from `theme`, mirroring the reference's cleaner approach.
#
# CRITICAL: opencode CRASHES on `null` and on the per-role value "system" (tested,
# build 1.18.16). The ONLY inheritance token we emit is the string "none"; every
# other value is a def-name resolving to hex. Never emit null or "system".
#
# Palette-schema gaps vs. the reference (documented choices; our schema has only
# accent/accent2, no distinct 3rd/4th accent like rose-pine's rose/pine):
#   * opencode `accent` role  -> palette accent2  (ref used a distinct "rose")
#   * opencode `info` role     -> palette accent2 (ref used a distinct "pine")
#   * markdownLinkText/ImageText (ref pine)  -> accent2
#   * markdownStrong / syntaxNumber (ref rose) -> accent2
# accent2 is the closest existing key in each case; kept consistent so the theme
# reads coherently without inventing colors the palette doesn't define.
# -----------------------------------------------------------------------------
render_opencode() {
  pf=$1; name=$2

  mkdir -p "$OPENCODE_THEMES_DIR"
  jq -n --slurpfile p "$pf" '
    ($p[0].dark)  as $d |
    ($p[0].light) as $l |
    # def d <- named palette color, carrying both modes, keyed by palette key.
    def d(k): { dark: $d[k], light: $l[k] };
    # r <- a theme role pointing at a def name (same name for both modes).
    def r($n): { dark: $n, light: $n };
    {
      "$schema": "https://opencode.ai/theme.json",
      # Named palette colors (both modes). "none" is NOT a def -- it is emitted
      # inline on the roles that inherit the terminal background.
      "defs": {
        "bg":       d("bg"),
        "surface":  d("surface"),
        "overlay":  d("overlay"),
        "muted":    d("muted"),
        "subtle":   d("subtle"),
        "fg":       d("fg"),
        "accent":   d("accent"),
        "accent2":  d("accent2"),
        "warn":     d("warn"),
        "error":    d("error"),
        "ok":       d("ok")
      },
      "theme": {
        "primary":            r("accent"),
        "secondary":          r("accent2"),
        "accent":             r("accent2"),
        "error":              r("error"),
        "warning":            r("warn"),
        "success":            r("ok"),
        "info":               r("accent2"),
        "text":               r("fg"),
        "textMuted":          r("muted"),

        # LAYERED backgrounds: base inherits the terminal; panel/element use
        # palette layers. "none" is a literal string (never null / "system").
        # (No backgroundMenu: the reference theme omits it, and we keep exact
        # role parity with rosepine-layered.json.)
        "background":         { "dark": "none", "light": "none" },
        "backgroundPanel":    r("surface"),
        "backgroundElement":  r("overlay"),

        "border":             r("overlay"),
        "borderActive":       r("accent"),
        "borderSubtle":       r("muted"),

        "diffAdded":            r("ok"),
        "diffRemoved":          r("error"),
        "diffContext":          r("subtle"),
        "diffHunkHeader":       r("subtle"),
        "diffHighlightAdded":   r("accent2"),
        "diffHighlightRemoved": r("error"),
        "diffAddedBg":          r("surface"),
        "diffRemovedBg":        r("surface"),
        "diffContextBg":        { "dark": "none", "light": "none" },
        "diffLineNumber":       r("muted"),
        "diffAddedLineNumberBg":   r("surface"),
        "diffRemovedLineNumberBg": r("surface"),

        "markdownText":           r("fg"),
        "markdownHeading":        r("accent"),
        "markdownLink":           r("accent2"),
        "markdownLinkText":       r("accent2"),
        "markdownCode":           r("warn"),
        "markdownBlockQuote":     r("subtle"),
        "markdownEmph":           r("warn"),
        "markdownStrong":         r("accent2"),
        "markdownHorizontalRule": r("muted"),
        "markdownListItem":       r("accent"),
        "markdownListEnumeration":r("accent2"),
        "markdownImage":          r("accent2"),
        "markdownImageText":      r("accent2"),
        "markdownCodeBlock":      r("fg"),

        "syntaxComment":     r("muted"),
        "syntaxKeyword":     r("accent"),
        "syntaxFunction":    r("accent2"),
        "syntaxVariable":    r("fg"),
        "syntaxString":      r("warn"),
        "syntaxNumber":      r("accent2"),
        "syntaxType":        r("accent2"),
        "syntaxOperator":    r("subtle"),
        "syntaxPunctuation": r("subtle")
      }
    }
  ' >"$OPENCODE_THEMES_DIR/$name.json"
}

# -----------------------------------------------------------------------------
# tmux: a status-bar styling conf per mode. tmux has no native theme registry,
# so tmux.conf sources one of these by filename. Structure mirrors the original
# inline block; the #{@agent_glyphs} references belong to the agent-status
# feature and are preserved verbatim.
#
# Terminal-inherit philosophy (same idea as the layered opencode theme): the
# bar's BASE background inherits the terminal via tmux's `bg=default`, so the bar
# blends into the terminal rather than painting a hardcoded palette bg. What
# stays palette-colored: all foreground text, and the segments meant to stand out
# -- the session-name block (accent bg) and the active window (overlay bg). Pane
# borders, message-style and mode-style keep palette hex; those aren't part of
# the bar backdrop. If `bg=default` ever reads worse than a subtle offset, the
# palette `surface` hex is the intended fallback for status-style bg.
# -----------------------------------------------------------------------------
render_tmux() {
  pf=$1; name=$2; mode=$3
  bg=$(g "$pf" "$mode" bg)
  fg=$(g "$pf" "$mode" fg)
  overlay=$(g "$pf" "$mode" overlay)
  muted=$(g "$pf" "$mode" muted)
  subtle=$(g "$pf" "$mode" subtle)
  accent=$(g "$pf" "$mode" accent)
  accent2=$(g "$pf" "$mode" accent2)
  warn=$(g "$pf" "$mode" warn)
  selection_bg=$(g "$pf" "$mode" selection_bg)

  mkdir -p "$TMUX_THEMES_DIR"
  cat >"$TMUX_THEMES_DIR/$name-$mode.conf" <<EOF
# GENERATED by dotfiles/themes/render.sh -- do not edit.
# palette: $name   mode: $mode
# Status-bar styling. tmux has no native theme registry; tmux.conf sources one
# of these by filename. Structure mirrors the original inline block; colors come
# from the palette. #{@agent_glyphs} is the agent-status overlay and is preserved.
#
# The bar's BASE background inherits the terminal (bg=default) so it blends in;
# only the standout segments (session-name accent block, active window) paint a
# palette bg. Foreground text stays palette-colored throughout.

set -g status on
set -g status-interval 5
set -g status-position top
set -g status-justify left

# Overall bar background inherits the terminal (bg=default); fg is palette text.
set -g status-style "bg=default,fg=$fg"

# Left: session name on an accent background. The trailing separator returns to
# the inherited terminal bg so the rest of the bar blends in.
set -g status-left-length 40
set -g status-left "#[bg=$accent,fg=$bg,bold] #S #[bg=default,fg=$accent]"

# Right: hostname then date/time, muted so it doesn't shout.
set -g status-right-length 80
set -g status-right "#[fg=$accent2] #H #[fg=$muted]| #[fg=$subtle]%Y-%m-%d #[fg=$fg]%H:%M "

# Window list: inactive windows muted, the active one highlighted.
# #{@agent_glyphs} is the agent-status overlay (one glyph per running agent in
# the window; empty when none). #W is the real window name.
setw -g window-status-format "#[fg=$muted] #I:#W #{@agent_glyphs}"
setw -g window-status-current-format "#[bg=$overlay,fg=$warn,bold] #I:#W #{@agent_glyphs}"
setw -g window-status-separator ""

# Pane borders: subtle for inactive, accent2 for the active pane.
set -g pane-border-style "fg=$overlay"
set -g pane-active-border-style "fg=$accent2"

# Messages / command prompt line.
set -g message-style "bg=$overlay,fg=$fg"
set -g message-command-style "bg=$overlay,fg=$fg"

# Copy-mode selection highlight.
setw -g mode-style "bg=$selection_bg,fg=$fg"
EOF
}

# render_palette <palette-file> <name>
render_palette() {
  pf=$1
  name=$2
  if [ ! -f "$pf" ]; then
    printf 'render.sh: error: no palette file: %s\n' "$pf" >&2
    return 1
  fi
  if ! jq -e '.dark and .light' "$pf" >/dev/null 2>&1; then
    printf 'render.sh: error: palette %s missing dark/light keys or invalid JSON\n' "$pf" >&2
    return 1
  fi

  render_wezterm "$pf" "$name" dark
  render_wezterm "$pf" "$name" light
  render_nvim    "$pf" "$name" dark
  render_nvim    "$pf" "$name" light
  render_opencode "$pf" "$name"
  render_tmux    "$pf" "$name" dark
  render_tmux    "$pf" "$name" light

  printf '  rendered %s -> wezterm/nvim/opencode/tmux\n' "$name"
}

# resolve_and_render <arg>  -- arg is a NAME (palettes/<name>.json) or a PATH.
resolve_and_render() {
  arg=$1
  # A path: contains a slash, or ends in .json, or exists as a file as given.
  case "$arg" in
    */* | *.json)
      if [ ! -f "$arg" ]; then
        printf 'render.sh: error: no such palette file: %s\n' "$arg" >&2
        return 1
      fi
      name=$(basename "$arg" .json)
      render_palette "$arg" "$name"
      ;;
    *)
      pf="$PALETTES_DIR/$arg.json"
      if [ ! -f "$pf" ]; then
        printf 'render.sh: error: no baked-in palette named %s (looked for %s)\n' "$arg" "$pf" >&2
        printf '  available:\n' >&2
        for p in "$PALETTES_DIR"/*.json; do
          [ -e "$p" ] || continue
          printf '    %s\n' "$(basename "$p" .json)" >&2
        done
        printf '  (or pass a path to a .json palette file)\n' >&2
        return 1
      fi
      render_palette "$pf" "$arg"
      ;;
  esac
}

main() {
  if [ "$#" -eq 0 ]; then
    printf 'render.sh: error: a palette name or path is required (or --all).\n' >&2
    printf 'Usage: render.sh <name|path.json> | --all\n' >&2
    exit 2
  fi
  case "$1" in
    --all)
      for pf in "$PALETTES_DIR"/*.json; do
        [ -e "$pf" ] || continue
        name=$(basename "$pf" .json)
        render_palette "$pf" "$name"
      done
      ;;
    -h | --help)
      printf 'Usage: render.sh <name|path.json> | --all\n'
      printf '  <name>       render palettes/<name>.json (baked-in public palette)\n'
      printf '  <path.json>  render an arbitrary palette file (e.g. a local brand)\n'
      printf '  --all        render every baked-in palette in palettes/\n'
      ;;
    *)
      resolve_and_render "$1"
      ;;
  esac
}

main "$@"
